const images = {
    avatar: require('../images/avatar-01.png'),
    avatar_bg: require('../images/avatar_bg.png'),
    avatar_fg: require('../images/avatar_fg.png'),
    fight_bg: require('../images/fight_bg.png'),
    rank_button_bg: require('../images/rank_button_bg.png'),
    rank_item_bg: require('../images/rank_item_bg.png'),
    level01: require('../images/level01.png'),
    level01_fbg: require('../images/level01_fbg.png'),
    level03_fbg: require('../images/level03_fbg.png'),
    level04_bg: require('../images/level04_bg.png'),
    level_bg: require('../images/level_bg.png'),
    level_fbg: require('../images/level_fbg.png'),
    level_panel: require('../images/level_panel.png'),
    monkey1: require('../images/monkey1.png'),
    monkey2: require('../images/monkey2.png'),
    monkey3: require('../images/monkey3.png'),
    panel_bg: require('../images/panel_bg.png'),
    pass_seal: require('../images/pass_seal.png'),
    not_pass: require('../images/not_pass.png'),

    rank_bg: require('../images/rank_bg.png'),
    stage00: require('../images/stage00.jpg'),
    stage01: require('../images/stage01.png'),
    tangseng: require('../images/tangseng.png'),
    modal_bg: require('../images/modal_bg.png'),
    level_avatar_bg: require('../images/level_avatar_bg.png'),
    level_avatar_fg: require('../images/level_avatar_fg.png'),
    power_button_bg: require('../images/power_button_bg.png'),

    level_01_s:require('../images/level/level-avatar-09.png'),
    level_02_s:require('../images/level/level-avatar-12.png'),
    level_03_s:require('../images/level/level-avatar-16.png'),
    level_04_s:require('../images/level/level-avatar-18.png'),
    level_05_s:require('../images/level/level-avatar-20.png'),
    level_06_s:require('../images/level/level-avatar-28.png'),
    level_07_s:require('../images/level/level-avatar-42.png'),
    level_08_s:require('../images/level/level-avatar-48.png'),
    level_09_s:require('../images/level/level-avatar-49.png'),
    level_10_s:require('../images/level/level-avatar-59.png'),

    level_01:require('../images/level/level-09.png'),
    level_02:require('../images/level/level-12.png'),
    level_03:require('../images/level/level-16.png'),
    level_04:require('../images/level/level-18.png'),
    level_05:require('../images/level/level-20.png'),
    level_06:require('../images/level/level-28.png'),
    level_07:require('../images/level/level-42.png'),
    level_08:require('../images/level/level-48.png'),
    level_09:require('../images/level/level-49.png'),
    level_10:require('../images/level/level-59.png'),

    start_button: require('../images/start_all.png'),
    buy_power_change: require('../images/buy_power_change.png'),
    buy_power_num: require('../images/buy_power_num.png'),

}

export default images
